# Generated by Django 3.1 on 2020-08-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200831_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
